variables:
    - &platforms 'linux/amd64,linux/arm64'
    - &golang 'golang:1.18'

pipeline:
  vendor:
    image: *golang
    commands: go mod vendor

  test:
    image: *golang
    commands: go test -cover ./...

  publish-dryrun:
    image: woodpeckerci/plugin-docker-buildx:v20.10.18
    settings:
      platforms: *platforms
      repo: woodpeckerci/plugin-docker-buildx
      dockerfile: Dockerfile.multiarch
      dry_run: true
    when:
      event: pull_request
      branch: main

  publish:
    image: woodpeckerci/plugin-docker-buildx:v20.10.18
    settings:
      platforms: *platforms
      repo: woodpeckerci/plugin-docker-buildx
      auto_tag: true
      dockerfile: Dockerfile.multiarch
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event: [push, tag, cron]
      branch: main
