clone:
  git:
    image: techknowlogick/drone-git:latest

pipeline:
  publish:
    image: plugins/kaniko
    repo: foo/bar
    no-push: true
    tags: latest
    username: foo
    password: bar
    dockerfile: Dockerfile
