branches: main

variables:
    - &platforms 'linux/amd64,linux/arm64'

pipeline:
  dryrun:
    image: woodpeckerci/plugin-docker-buildx:v20.10.18
    settings:
      platforms: *platforms
      repo: woodpeckerci/plugin-docker-buildx
      dockerfile: Dockerfile.multiarch
      dry_run: true
    when:
      event: pull_request

  publish:
    image: woodpeckerci/plugin-docker-buildx:v20.10.18
    settings:
      platforms: *platforms
      repo: woodpeckerci/plugin-docker-buildx
      tags: latest, ${CI_COMMIT_TAG}
      dockerfile: Dockerfile.multiarch
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event: [push, tag, cron]
      branch: main
