pipeline:
  publish:
    image: plugins/kaniko
    settings:
      repo: woodpeckerci/plugin-docker-buildx
      tags: latest
      dockerfile: Dockerfile
    secrets:
      - source: docker_username
        target: plugin_username
      - source: docker_password
        target: plugin_password
