pipeline:
  publish:
    image: plugins/kaniko
    settings:
      repo: woodpeckerci/plugin-docker-buildx
      tags: latest
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password