clone:
  git:
    image: techknowlogick/drone-git:latest

pipeline:
  publish:
    image: plugins/kaniko
    repo: woodpeckerci/plugin-docker-buildx
    tags: latest
    secrets:
      - source: docker_username
        target: plugin_username
      - source: docker_password
        target: plugin_password
    dockerfile: Dockerfile
