pipeline:
  build:
    image: golang:1.17
    commands:
      - "[ -z \"${DRONE_TAG}\" ] && BUILD_VERSION=${DRONE_COMMIT_SHA:0:8} || BUILD_VERSION=${DRONE_TAG##v}"
      - go build -v -a -tags netgo ./cmd/docker-buildx

  publish:
    image: plugins/docker
    repo: foo/bar
